/**
 * Automatically generated build information （。＾▽＾）
 *
 * This file is automatically generated by the `generate-build-info.js` script,
 * only used to provide build information for the project!
 * 
 * Script author: 白澪·洛丝塔亚(mio@chyan.moe)
 * 
 * File created on : 2025-05-04T13:45:39.343Z
 */
export const buildInfo = {
  "git": {
    "repository": "https://github.com/Miourasaki/kagamie.git",
    "commit": {
      "hash": "d461891",
      "hashFull": "d4618916e7447d5f7c6cbba58a6b8ead11f59c0e",
      "message": "fix: 对不起😭忘记加忽略文件了",
      "summary": "fix: 对不起😭忘记加忽略文件了",
      "description": "",
      "date": "Sun May 4 21:43:58 2025 +0800",
      "author": "白澪 · 卡丝蕾特",
      "authorEmail": "mio@chyan.moe"
    },
    "branch": "master",
    "tag": "d461891"
  },
  "buildDate": "2025-05-04T13:45:39.343Z",
  "buildTimestamp": 1746366339343,
  "node": {
    "version": "v20.14.0",
    "project": {
      "name": "kagamie",
      "version": "0.1.0.0"
    }
  },
  "dependencies": {
    "@radix-ui/react-avatar": "^1.1.7",
    "@radix-ui/react-context-menu": "^2.2.12",
    "@radix-ui/react-dialog": "^1.1.11",
    "@radix-ui/react-menubar": "^1.1.12",
    "@radix-ui/react-scroll-area": "^1.2.6",
    "@radix-ui/react-slot": "^1.2.0",
    "@swc/core": "^1.11.24",
    "@swc/helpers": "^0.5.17",
    "@types/mongodb": "^4.0.7",
    "@types/next": "^9.0.0",
    "@types/socket.io": "^3.0.2",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "cross-env": "^7.0.3",
    "express": "^5.1.0",
    "lucide-react": "^0.503.0",
    "mongodb": "^6.16.0",
    "next": "15.3.1",
    "nodemon": "^3.1.10",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "socket.io": "^4.8.1",
    "socket.io-client": "^4.8.1",
    "tailwind-merge": "^3.2.0",
    "ts-node": "^10.9.2"
  },
  "devDependencies": {
    "@tailwindcss/postcss": "^4",
    "@types/express": "^5.0.1",
    "@types/node": "^22.15.3",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "tailwindcss": "^4",
    "tw-animate-css": "^1.2.8",
    "typescript": "^5.8.3"
  },
  "platform": "win32"
}